#' Generate or modify input_data_default.csv content
#'
#' This function creates the template of input_data_default.csv from scratch
#' and replaces parameter values with user-specified inputs.
#' It returns the full CSV content as a character vector, so that the user
#' can write it to a file with writeLines().
#'
#' @export
input_data_default <- function(
  Cab = 40, Cca = 10, Cdm = 0.012, Cw = 0.009, Cs = 0, Cant = 1,
  Cp = 0, Cbc = 0, N = 1.5, rho_thermal = 0.01, tau_thermal = 0.01,
  Vcmax25 = 60, BallBerrySlope = 8, BallBerry0 = 0.01, Type = 0, kV = 0.64,
  Rdparam = 0.015, Kn0 = 2.48, Knalpha = 2.83, Knbeta = 0.114,
  Tyear = 15, beta = 0.51, kNPQs = 0, qLs = 1, stressfactor = 1, fqe = 0.01,
  spectrum = 1, rss = 500, rs_thermal = 0.06, cs = 1180, rhos = 1800,
  lambdas = 1.55, SMC = 25, BSMBrightness = 0.5, BSMlat = 25, BSMlon = 45,
  LAI = 3, hc = 2, LIDFa = -0.35, LIDFb = -0.15, leafwidth = 0.1,
  Cv = 1, crowndiameter = 1,
  z = 5, Rin = 600, Ta = 20, Rli = 300, p = 970, ea = 15, u = 2,
  Ca = 410, Oa = 209,
  zo = 0.25, d = 1.34, Cd = 0.3, rb = 10, CR = 0.35, CD1 = 20.6,
  Psicor = 0.2, CSSOIL = 0.01, rbs = 10, rwc = 0,
  startDOY = 20060618, endDOY = 20300101, LAT = 51.55, LON = 5.55,
  timezn = 1, tts = 30, tto = 0, psi = 0
) {
  template <- c(
    "PROSPECT,",
    paste0("Cab,", Cab),
    paste0("Cca,", Cca),
    paste0("Cdm,", Cdm),
    paste0("Cw,", Cw),
    paste0("Cs,", Cs),
    paste0("Cant,", Cant),
    paste0("Cp,", Cp),
    paste0("Cbc,", Cbc),
    paste0("N,", N),
    paste0("rho_thermal,", rho_thermal),
    paste0("tau_thermal,", tau_thermal),
    ",",
    "Leaf_Biochemical,",
    paste0("Vcmax25,", Vcmax25),
    paste0("BallBerrySlope,", BallBerrySlope),
    paste0("BallBerry0,", BallBerry0),
    paste0("Type,", Type),
    paste0("kV,", kV),
    paste0("Rdparam,", Rdparam),
    paste0("Kn0,", Kn0),
    paste0("Knalpha,", Knalpha),
    paste0("Knbeta,", Knbeta),
    " ,",
    "Leaf_Biochemical_magnani,",
    paste0("Tyear,", Tyear),
    paste0("beta,", beta),
    paste0("kNPQs,", kNPQs),
    paste0("qLs,", qLs),
    paste0("stressfactor,", stressfactor),
    ",",
    "Fluorescence,",
    paste0("fqe,", fqe),
    ",",
    "Soil,",
    paste0("spectrum,", spectrum),
    paste0("rss,", rss),
    paste0("rs_thermal,", rs_thermal),
    paste0("cs,", cs),
    paste0("rhos,", rhos),
    paste0("lambdas,", lambdas),
    paste0("SMC,", SMC),
    paste0("BSMBrightness,", BSMBrightness),
    paste0("BSMlat,", BSMlat),
    paste0("BSMlon,", BSMlon),
    ",",
    "Canopy,",
    paste0("LAI,", LAI),
    paste0("hc,", hc),
    paste0("LIDFa,", LIDFa),
    paste0("LIDFb,", LIDFb),
    paste0("leafwidth,", leafwidth),
    paste0("Cv,", Cv),
    paste0("crowndiameter,", crowndiameter),
    ",",
    "Meteo,",
    paste0("z,", z),
    paste0("Rin,", Rin),
    paste0("Ta,", Ta),
    paste0("Rli,", Rli),
    paste0("p,", p),
    paste0("ea,", ea),
    paste0("u,", u),
    paste0("Ca,", Ca),
    paste0("Oa,", Oa),
    ",",
    "Aerodynamic,",
    paste0("zo,", zo),
    paste0("d,", d),
    paste0("Cd,", Cd),
    paste0("rb,", rb),
    paste0("CR,", CR),
    paste0("CD1,", CD1),
    paste0("Psicor,", Psicor),
    paste0("CSSOIL,", CSSOIL),
    paste0("rbs,", rbs),
    paste0("rwc,", rwc),
    ",",
    "timeseries,",
    paste0("startDOY,", startDOY),
    paste0("endDOY,", endDOY),
    paste0("LAT,", LAT),
    paste0("LON,", LON),
    paste0("timezn,", timezn),
    ",",
    "Angles,",
    paste0("tts,", tts),
    paste0("tto,", tto),
    paste0("psi,", psi)
  )
  return(template)
}

# End